class Constants {
  static String iconMasspa = 'assets/icon-masspa/bg-login.svg';
  static String logoWithText = 'images/logoWithText.svg';
}

class ConstantsApi {
  static Map<String, String> header = {
    'apiKey':
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjowLjQxMzA3NDk2NzgyMjMxMjgsImlhdCI6MTU4NDQyOTAwOSwiZXhwIjoxNjcwODI5MDA5fQ.5RZBZtjorqEFiYUwg5a43tJini_MfFJ43YGBeYEBmsc',
    'Authorization':
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1widXNlckNvZGVcIjpcIjUzN2E3NzQxLWJmMTktNDFlNC1iZmU1LTQ3NTQ2MDE1NDY3NFwiLFwic29jaWFsSWRcIjpudWxsLFwic29jaWFsVHlwZVwiOlwic3lzdGVtXCIsXCJ0eXBlQWNjb3VudFwiOm51bGwsXCJ1c2VybmFtZVwiOlwiOTMyODc5ODEzXCIsXCJmaXJzdE5hbWVcIjpcIk5nYVwiLFwibGFzdE5hbWVcIjpcIkh14buzbmggLSBUZXN0IFwiLFwiZW1haWxcIjpcIm5nYTE4MTA5NkBnbWFpbC5jb21cIixcImFkZHJlc3NcIjpcInRlc3QgXCIsXCJjb3VudHJ5Q29kZVwiOlwiKzg0XCIsXCJkb2JcIjpcIjIwMjAtMDUtMDFcIixcImlzTm90aWZpY2F0aW9uXCI6MSxcImFjdGl2ZVwiOjEsXCJnb29nbGVVcmxcIjpudWxsLFwiZmFjZWJvb2tVcmxcIjpudWxsLFwidWlkRmlyZUJhc2VcIjpudWxsLFwiYXZhdGFySW1hZ2VcIjpcImh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS9tYXNzcGEtZGV2LmFwcHNwb3QuY29tL2F2YXRhci81MzdhNzc0MS1iZjE5LTQxZTQtYmZlNS00NzU0NjAxNTQ2NzQvNTM3YTc3NDEtYmYxOS00MWU0LWJmZTUtNDc1NDYwMTU0Njc0XzE2MTc5NTU2NTA2MjQuanBnXCIsXCJtb2JpbGVcIjpcIjA5MzI4Nzk4MTM0XCIsXCJzZXhcIjoxLFwibmlja05hbWVcIjpudWxsLFwibG9naW5UaW1lXCI6MTYyMzAzNzE5NzE4MixcImNyZWF0ZWRBdFwiOjE1NTgzNjEwMzg5NTEsXCJ1cGRhdGVkQXRcIjoxNjIyODAxNzQwMjU2LFwicm9sZUlkXCI6e1wibG9naW5Gcm9udGVuZFwiOjEsXCJsb2dpbkFkbWluXCI6MSxcInJvbGVzXCI6W3tcInJvbGVcIjpcIm93bmVyU3BhXCIsXCJzZXJ2aWNlQ29kZVwiOlwiOWRmZTAxODAtMzAzOS0xMWVhLTg1YmItODE1Y2RmYjFjOWZiXCJ9LHtcInJvbGVcIjpcIm93bmVyU3BhXCIsXCJzZXJ2aWNlQ29kZVwiOlwiZjYzZGQ1MjAtZjhjMy0xMWVhLTk3MWEtZTM3ZTg1YjI5YTZlXCJ9XSxcInJvbGVcIjpcIm93bmVyU3BhXCIsXCJzZXJ2aWNlQ29kZVwiOlwiOWRmZTAxODAtMzAzOS0xMWVhLTg1YmItODE1Y2RmYjFjOWZiXCIsXCJzcGFOYW1lXCI6XCJOR09DIFNQQVwiLFwiYnJhbmNoQ29kZVwiOlwiY2M1ZDlkYWYtMzVkMi0xMWVhLTk2ZmItMDI0MmFjMTIwMDAzXCIsXCJicmFuY2hOYW1lXCI6XCJOR09DIFNQQVwifX0iLCJpYXQiOjE2MjMyNjAxNDAsImV4cCI6MTYyMzg2NDk0MH0.FeY3nDGei_8IxMoRrNHoWWNEtUP6qu-ww-tyMah5Bus',
    "Accept": "application/json",
    "Content-type": "application/json",
  };

  static String baseUrl = 'https://dev-api.masspa.vn/';
}
